fixed some things but still doesnt work
Error that gets spit out:
ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-env' from 'C:\Users\Home\Documents\GitHub\CubTime'
    at Function.module.exports [as sync] (C:\Users\Home\Documents\GitHub\CubTime\node_modules\resolve\lib\sync.js:74:15)
    at resolveStandardizedName (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePreset (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
    at loadPreset (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\files\plugins.js:77:20)
    at createDescriptor (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at items.map (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-chain.js:320:26)
    at C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-chain.js:283:7
    at buildRootChain (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-chain.js:120:22)
    at loadPrivatePartialConfig (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\partial.js:85:55)
    at Object.loadPartialConfig (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\partial.js:110:18)
    at Object.<anonymous> (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:3:103)
    at _next (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:5:194)
    at C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:5:97)
    at Object._loader (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:224:18)
    at Object.loader (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:60:18)
    at Object.<anonymous> (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:55:12)
 @ multi ./src/index.js main[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! beartime-web@1.1.0 dev: `webpack --progress --hide-modules && webpack-dev-server --inline --hot`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the beartime-web@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\Roaming\npm-cache\_logs\2019-11-09T03_07_53_420Z-debug.log

C:\Users\Home\Documents\GitHub\CubTime>npm run dev

> beartime-web@1.1.0 dev C:\Users\Home\Documents\GitHub\CubTime
> webpack --progress --hide-modules && webpack-dev-server --inline --hot

Hash: e0cccfe5e92bc08a767e
Version: webpack 4.41.2
Time: 669ms
Built at: 11/08/2019 9:09:34 PM
 1 asset
Entrypoint main = build.js

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-env' from 'C:\Users\Home\Documents\GitHub\CubTime'
    at Function.module.exports [as sync] (C:\Users\Home\Documents\GitHub\CubTime\node_modules\resolve\lib\sync.js:74:15)
    at resolveStandardizedName (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePreset (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
    at loadPreset (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\files\plugins.js:77:20)
    at createDescriptor (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at items.map (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-chain.js:320:26)
    at C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-chain.js:283:7
    at buildRootChain (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\config-chain.js:120:22)
    at loadPrivatePartialConfig (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\partial.js:85:55)
    at Object.loadPartialConfig (C:\Users\Home\Documents\GitHub\CubTime\node_modules\@babel\core\lib\config\partial.js:110:18)
    at Object.<anonymous> (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:3:103)
    at _next (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:5:194)
    at C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:5:97)
    at Object._loader (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:224:18)
    at Object.loader (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:60:18)
    at Object.<anonymous> (C:\Users\Home\Documents\GitHub\CubTime\node_modules\babel-loader\lib\index.js:55:12)
 @ multi ./src/index.js main[0]
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! beartime-web@1.1.0 dev: `webpack --progress --hide-modules && webpack-dev-server --inline --hot`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the beartime-web@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\Roaming\npm-cache\_logs\2019-11-09T03_09_35_017Z-debug.log